### PR TITLE
[CAR-1508]  fix entity synonym recognition

### PR DESCRIPTION
**Pull request by odannyc**
Jira Ticket: 
https://carlabs.atlassian.net/browse/CAR-1508

Description:
It turns out that the way rasa does entity recognition is through a library called [CRF](http://www.chokkan.org/software/crfsuite/). It can extract entities even if they're not in the training data or synonyms, and this was causing issues with converting synonyms to actual entity values because those entities extracted by CRF weren't found in the synonym list.
There were a couple of solutions I had in mind:

- Add all possible synonyms to the Dialogflow synonym list.
- Create my own entity extractor which does exact matching on entity values and synonyms
- Add fuzzy matching with `ner_crf` and `ner_synonym` pipeline

The first option doesn't scale very well because it is a manual process.
The second option is what I was gonna go with but eventually thought that we might want to keep `ner_crf` because of the way it extracts entities. 
I finally decided fuzzy matching was the best way to go because we don't have to specify every way an entity could be spelled, fuzzy matching will take care of matching that with the synonym and entity value. Also, its a lot less code I had to write ;p

### CODE REVIEW

**Comment by barakyo** [comment]
@odannyc my only worry is that this is a forked repo. We currently have an open PR with them to get our changes merged upstream. Maybe @akingbadeayobami  or @nimf have suggestions for how we can do this with [Custom Componenters](https://rasa.com/docs/nlu/customcomponents/) so we don't have to actually make changes directly to RASA's code base?

**Comment by blakeandrewwood** [comment]
@barakyo We started a repo called Innatis. https://github.com/Revmaker/innatis

This was suppose to be where we add all of our external components for rasa. However I am not sure if it's currently being used in our current instance of rasa.

We can add our external components here and pull it from pypi.

**Comment by nimf** [comment]
Yeah, we have https://github.com/Revmaker/innatis this repo where we put things that won't make it into Rasa for a long time or even never.
If we can't have this functionality (fuzzy matching) within our `composite_entity_extractor` I think we can have a forked/updated ner_synonyms with another name in the innatis repo.

**Comment by nimf** [comment]
@blakeandrewwood you are right, we haven't switched to innatis yet, but we should.

**Comment by samhavens** [comment]
Confirming that composite entity extraction via Innatis and off-the-shelf rasa-nlu works. I checked a few days ago. @nimf is right that this can go in the Innatis version of the entity extractor. I guess ideally it would be behind a config flag, `fuzzy_matching: True` or something...

**Comment by samhavens** [comment]
@odannyc I think you'd add fuzzy matching in this function... https://github.com/Revmaker/innatis/blob/master/innatis/extractors/composite_data_extractor.py#L84

**Comment by nimf** [comment]
As long as it is fuzzy, I believe the config should be: `fuzzy_matching: maybe`

Just kidding. +1 for the config

**Comment by barakyo** [comment]
Given the discussion in here it sounds like we need to do a few things:

1. Create a ticket to switch to Innatis
2. This functionality should ported into the Composite Data Extractor within Innatis

**Pull request closed without merging**
